### ISSUE TITLE
Textual directions UI should group directions by floor

### ISSUE THREAD

**Issue by dgorbunov** [CS3733-2024-TeamO/OliveOuroboros#248]
Ideally, each floor has a dropdown of text directions on that floor. The dropdown is initially closed.

**Comment by cemasucci** [comment]
Animation collapsing is done based off a max-height variable because I can only figure out how to animate using rem or px rather than precents. The max-height is set to 500rem when open.
This means that when collapsing, there might be a slight delay since the max height is being shortened from 500rem rather the the set height of the FloorDirection div.
This also means that if directions on a single floor take up more than 500 rem of space, they will be cut off at that limit. I don't think this would ever happen unless using breadth or depth first search.

**Comment by dgorbunov** [comment]
<img width="278" alt="image" src="https://github.com/CS3733-2024-TeamO/OliveOuroboros/assets/38931252/47a04ed2-e89c-4fce-8430-29bb8c934345">

@cemasucci
The app crashes when selecting DFS with these nodes. 
`Rendered more hooks than during the previous render.`

**Comment by cemasucci** [comment]
I think the DFS issue is fixed. The floor Sections were componentized

But the animation issue is still present

**Comment by cemasucci** [comment]
Just found out some routes are not calculating but i'm not sure why
![image](https://github.com/CS3733-2024-TeamO/OliveOuroboros/assets/163580812/182f2ab4-a6b6-4f7f-bbfa-94a8eaa7cd60)

This was the path I used
![image](https://github.com/CS3733-2024-TeamO/OliveOuroboros/assets/163580812/f723c271-1ad2-4e0b-9c5d-58a923eab14b)

**Comment by FrancescoDM6** [comment]
Completed by Colin
